In [2]:
import numpy as np

escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [3]:
vector = np.array([30, 29, 42, 35, 36, 42, 41])
print(vector)

[30 29 42 35 36 42 41]


In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [8]:
array_arrange = np.arange(10)
print(array_arrange)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
diag = np.diag([1, 2, 3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
random = np.random.random((2, 3))
print(random)

[[0.07793984 0.58078972 0.27914511]
 [0.92094359 0.81233419 0.3623868 ]]
