In [2]:
import numpy as np

escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [3]:
vector = np.array([30, 29, 42, 35, 36, 42, 41])
print(vector)

[30 29 42 35 36 42 41]


In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [8]:
array_arrange = np.arange(10)
print(array_arrange)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
diag = np.diag([1, 2, 3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
random = np.random.random((2, 3))
print(random)

[[0.07793984 0.58078972 0.27914511]
 [0.92094359 0.81233419 0.3623868 ]]


In [15]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [16]:
z = np.array(3, dtype=np.uint8)
print(z)

3


In [20]:
double_array = np.array([[1, 2, 3], [4, 5, 6]], dtype="d")
print(double_array)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
z = z.astype(np.float64)
print(z)

3.0


In [22]:
array = np.array([[1, 2, 3], [4, 5, 6]])
add = np.sum(array)
print(add)

21


In [23]:
array = np.array([[1, 2, 3], [4, 5, 6]])
sum = np.sum(array)
print(sum)

21


In [24]:
mean = np.mean(array)
print(mean)

3.5


In [25]:
std = np.std(array)
print(std)

1.707825127659933
