In [2]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5])
print(array[1])
print(array[-1])

2
5


In [5]:
print(array[1:4])

[2 3 4]


In [9]:
array = np.array([10, 20, 30, 40, 50])
bool_index = array > 3
print(bool_index)

[ True  True  True  True  True]


In [10]:
index = [2, 3, 4]
print(array[index])

[30 40 50]


In [12]:
array = np.random.randint(0, 10, size=(3, 3))
print(array)
print(array[0, 1])

[[9 7 1]
 [2 2 9]
 [5 3 8]]
7


In [13]:
print(array[:2, :2])

[[9 7]
 [2 2]]
